#!/bin/bash

exec 2>&1

{{#if cfg.runtime.heapsize ~}}
export ES_HEAP_SIZE={{cfg.runtime.heapsize}}
{{/if ~}}
{{#if cfg.runtime.es_java_opts}}
export ES_JAVA_OPTS={{cfg.runtime.es_java_opts}}
{{/if ~}}
{{#if cfg.runtime.es_startup_sleep_time}}
export ES_STARTUP_SLEEP_TIME={{cfg.runtime.es_startup_sleep_time}}
{{/if ~}}
{{#if cfg.runtime.max_locked_memory}}
export MAX_LOCKED_MEMORY={{cfg.runtime.max_locked_memory}}
{{/if ~}}
{{#if cfg.runtime.max_open_files}}
export MAX_OPEN_FILES={{cfg.runtime.max_open_files}}
{{/if ~}}

exec elasticsearch --default.path.conf={{pkg.svc_config_path}}
