[drupal]
  site_name = "drupal"
  db_name = "drupal"
  account_name = "admin"
  account_password = "173467321476C32789777643T732V73117888732476789764376Lock"

[nginx]
  worker_processes = 4

  [nginx.events]
    worker_connections = 1024

  [nginx.http]
    keepalive_timeout = 60
    sendfile = "on"
    tcp_nodelay = "on"
    tcp_nopush = "on"

    [nginx.http.listen]
      port = 80