#!/bin/sh
jemalloc_path=$(find / -type f -name libjemalloc.so.2)
ln -sf $jemalloc_path "$(dirname $jemalloc_path)/libjemalloc.so.1"

if [ ! -f /var/opt/mssql/data/master.mdf ]; then
  SQLSERVR_SA_PASSWORD="{{cfg.sa_password}}" {{pkg.path}}/bin/sqlservr --setup 2>&1
fi

{{pkg.path}}/bin/mssql-conf accept-eula 2>&1
{{pkg.path}}/bin/mssql-conf set defaultdatadir {{pkg.svc_data_path}} 2>&1
{{pkg.path}}/bin/mssql-conf set defaultlogdir {{pkg.svc_data_path}} 2>&1
{{pkg.path}}/bin/mssql-conf set tcpport {{cfg.port}} 2>&1
