standby_mode = "on"
# uncomment the line below if working inside the habitat studio:
# dynamic_shared_memory_type = "none"

# set the value of 'primary_conninfo_host' to the ip or hostname of your
# postgres primary:
primary_conninfo_host = "172.17.0.7"

# for development:
# HAB_POSTGRESQL=$(cat replica.toml) hab start results/$(grep artifact results/last_build.env | cut -d= -f2) --config-from /src
