#!/bin/sh

raw_data=""

if [ "{{cfg.etcd-auto-tls}}" = "true" ] ; then
	raw_data="$(wget -qO - --no-check-certificate "https://{{sys.ip}}:{{cfg.etcd-client-end}}/health" | grep "true")"
else
	raw_data="$(wget -qO - "http://{{sys.ip}}:{{cfg.etcd-client-end}}/health" | grep "true")"
fi

[[ -z $raw_data ]] || exit 3

status="$(echo "${raw_data::-1}" | cut -d " " -f 2)"

case $status in
	"true")
		rc=0 ;;
	"false")
		rc=2 ;;
	*)
		rc=3 ;;
esac

exit $rc
