#!/bin/sh

{{~#if bind.prom}}
# setup a prometheus datasource
cp {{pkg.svc_config_path}}/datasource-prometheus.yaml {{pkg.svc_var_path}}/provisioning/datasources

# now cp the rendered dashboards to the var/dashboards/ dir
cp -rf {{pkg.svc_config_path}}/prometheus-*.json {{pkg.svc_var_path}}/dashboards/
{{~/if}}
