[cluster]
  name = "crate"

  [cluster.info]
    [cluster.info.update]
      interval = "30s"

  [cluster.graceful_stop]
    min_availability = "primaries"
    reallocate = "true"
    timeout = "2h"
    force = "false"

  [cluster.routing]
    [cluster.routing.allocation]
      enable = "all"
      allow_rebalance = "indices_all_active"
      cluster_concurrent_rebalance = "2"
      node_initial_primaries_recoveries = "4"
      node_concurrent_recoveries = "2"

    [cluster.routing.allocation.balance]
      shard = "0.45f"
      index = "0.5f"
      primary = "0.05f"
      threshold = "1.0f"

    [cluster.routing.allocation.disk]
      threshold_enabled = "true"

      [cluster.routing.allocation.disk.watermark]
        low = "85%"
	high = "90%"

[node]
  name = ""
  data = "true"
  client = "false"
  local = "false"

  [node.sql]
    read_only = "false"

[network]
  bind_host = ""
  publish_host = ""

[http]
  port = 4200
  publish_port = ""

  [http.cors]
    enabled = "false"
    allow-origin = ""
    max-age = "1728000"
    allow-methods = "OPTIONS, HEAD, GET, POST, PUT, DELETE"
    allow-headers = "X-Requested-With, Content-Type, Content-Length"
    allow-credentials = "false"

[transport]
  publish_port = ""

  [transport.tcp]
    port = 4300

[psql]
  port = 5432

[path]
  repo = ""

[plugins]
  mandatory = ""

[bootstrap]
  mlockall = "false"

[monitor]
  [monitor.jvm]
    [monitor.jvm.gc]
      [monitor.jvm.gc.young]
        warn = "1000ms"
	info = "1000ms"
	debug = "1000ms"

      [monitor.jvm.gc.old]
        warn = "1000ms"
	info = "1000ms"
	debug = "1000ms"

[es]
  [es.api]
    enabled = "false"

[blobs]
  path = ""

[repositories]
  [repositories.url]
    allowed_urls = ""
    supported_protocols = "http, https, ftp, file, jar"

[stats]
  enabled = "false"
  jobs_log_size = "10000"
  jobs_log_expiration = "0s"
  operations_log_size = "10000"
  operations_log_expiration = "0s"

  [stats.service]
    interval = "1h"

  [stats.breaker]
    [stats.breaker.log]
      [stats.breaker.log.jobs]
        limit = "5%"
      
      [stats.breaker.log.operations]
        limit = "5%"

[bulk]
  request_timeout = "1m"

[discovery]
  type = ""

  [discovery.azure]
    method = "vnet"

  [discovery.ec2]
    groups = ""
    any_group = "true"
    host_type = "private_ip"
    availability_zones = ""
    ping_timeput = "3s"
    endpoint = ""

  [discovery.srv]
    query = ""
    resolver = ""

  [discovery.zen]
    minimum_master_nodes = "1"
    ping_timeout = "3s"
    publish_timeout = "30s"

    [discovery.zen.ping]
      [discovery.zen.ping.unicast]
        hosts = ""

[cloud]
  [cloud.aws]
    access_key = ""
    secret_key = ""

  [cloud.azure]
    [cloud.azure.management]
      [cloud.azure.management.resourcegroup]
        name = ""

      [cloud.azure.management.subscription]
        id = ""

      [cloud.azure.management.tenant]
        id = ""

      [cloud.azure.management.app]
        id = ""
	secret = ""

[indices]
  [indices.breaker]
    [indices.breaker.query]
      limit = "60%"
      overhead = "1.09"

    [indices.breaker.fielddata]
      limit = "60%"
      overhead = "1.03"

    [indices.breaker.request]
      limit = "40%"
      overhead = "1.0"

  [indices.recovery]
    concurrent_streams = "3"
    file_chunk_size = "512kb"
    translog_ops = "1000"
    translog_size = "512kb"
    compress = "true"
    max_bytes_per_sec = "40mb"
    retry_delay_state_sync = "500ms"
    retry_delay_network = "5s"
    retry_activity_timeout = "15m"
    retry_internal_action_timeout = "15m"
    retry_internal_long_action_timeout = "30m"

  [indices.store]
    [indices.store.throttle]
      type = "merge"
      max_bytes_per_sec = "20mb"

[gateway]
  expected_nodes = "-1"
  recover_after_time = "5m"
  recover_after_nodes = "-1"
