---
driver:
  name: vagrant
  synced_folders:
    - [<%= File.join(ENV['PWD'], '..', '..')%>, '/tmp/repo-data']

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: 'secrets/fakey-mcfakerton'
  data_bags_path: './data_bags'

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[delivery_build::default]
      - recipe[test]
    attributes:
      delivery_build:
          delivery-cli:
            artifact: 'https://delivery-packages.s3.amazonaws.com/cli/delivery-cli-20150706022129-1.x86_64.rpm'
            checksum: '96ac99ed01466b8deb8d1c7366f4468dabf2282ad6b2ce7da8bd7edbc6ad673f'
