#!/bin/bash

exec 2>&1

export GEM_HOME="{{pkg.path}}/vendor/bundle/ruby/2.4.0"
export GEM_PATH="{{pkgPathFor "core/ruby"}}/lib/ruby/gems/2.4.0:{{pkgPathFor "core/bundler"}}:$GEM_HOME"

exec fluentd -c {{pkg.svc_config_path}}/fluent.conf
