#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update


echo "==> Unloading habitat service jarvus/postfix…"
hab sup unload jarvus/postfix
sleep 1


echo "==> Starting syslogd daemon…"
rm /dev/log
hab pkg exec core/busybox-static syslogd -n &
sleep 1


echo "==> Loading habitat service jarvus/postfix…"
hab sup start jarvus/postfix