pkg_name=pv
pkg_origin=core
pkg_license=('ARTISTIC 2.0')
pkg_version="1.6.6"
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_description="Pipe Viewer - is a terminal-based tool for monitoring the progress of data through a pipeline."
pkg_upstream_url="http://www.ivarch.com/programs/pv.shtml"
pkg_source="https://www.ivarch.com/programs/sources/pv-${pkg_version}.tar.bz2"
pkg_shasum="608ef935f7a377e1439c181c4fc188d247da10d51a19ef79bcdee5043b0973f1"
pkg_deps=(core/glibc)
pkg_build_deps=(core/make core/gcc)
pkg_bin_dirs=(bin)
