port = 10389

# Base DN for your LDAP server
suffix = "dc=my-domain,dc=com"

# DN for administrative user
rootdn = "cn=Manager,dc=my-domain,dc=com"

# Password for administrative user
rootpw = "secret"

# List of URLs to serve
url_list = "ldap://0.0.0.0:10389"

# Location of SSL certificate file
ssl_cert = ""

# Location of SSL key file
ssl_key = ""

# Location of CA certificate
ssl_ca = ""

# Which SSL Cipher suite to use
ssl_cipher_suite = ""
