#!/bin/sh

exec 2>&1

. "{{pkg.svc_config_path}}/env"

{{~#if cfg.rabbitmq.cluster.enabled}}
# Make sure that RabbitMQ started before we attempt to cluster
$SUP_CMD rabbitmqctl wait {{pkg.svc_var_path}}/db/rabbit@{{sys.hostname}}.pid
{{~#if svc.me.follower}}
{{~#with svc.leader}}
$SUP_CMD rabbitmqctl stop_app
$SUP_CMD rabbitmqctl join_cluster rabbit@{{sys.hostname}}
$SUP_CMD rabbitmqctl start_app
{{~/with}}
{{~/if}}
{{~/if}}
# sending TERM to ensure configuration is fully applied
kill -SIGTERM `cat {{pkg.svc_pid_file}}`
