#!{{pkgPathFor "core/bash"}}/bin/bash -e


{{#if svc.me.follower ~}}
# MySQL follower (aka "slave" in MySQL parlance) status
echo "[mysql] status: FOLLOWER my_ip: {{sys.ip}} leader_ip: {{svc.leader.sys.ip}}"
mysqladmin --defaults-extra-file={{pkg.svc_config_path}}/client.cnf --wait=5 status
mysql --defaults-extra-file={{pkg.svc_config_path}}/client.cnf -e "SHOW SLAVE STATUS" --auto-vertical-output | egrep "Master_Host|State|Running|Behind"

# TODO: have this error out if a $seconds_behind breaches a threshold multiple times
seconds_behind=$(mysql --defaults-extra-file={{pkg.svc_config_path}}/client.cnf -e "SHOW SLAVE STATUS" --auto-vertical-output | grep "Seconds_Behind_Master" | awk '{print $2}' )
if [[ $seconds_behind -gt 5 ]]; then
  echo "PROBLEM: this follower is $seconds_behind seconds behind the leader"
fi

{{else}}
echo "[mysql] status: LEADER my_ip: {{sys.ip}}"
mysqladmin --defaults-extra-file={{pkg.svc_config_path}}/client.cnf --wait=5 status
{{~/if}}
