#!/bin/bash
# shellcheck disable=2154

exec 2>&1

source "{{ pkg.svc_config_path }}/hook-helper.sh"

minio_splay_delay

if [ "$standalone" != "true" ] && [ ! -f "$run_good_hook" ]; then
    echo "Minio is not ready for bucket configuring. May be later"
    exit 1
fi

create_bucket
