#!{{pkgPathFor "core/bash"}}/bin/bash
#
shopt -s extglob

exec 2>&1

source {{pkg.svc_config_path}}/functions.sh

mkdir -p {{pkg.svc_config_path}}/conf.d
mkdir -p {{pkg.svc_var_path}}/pg_stat_tmp

# Auto-detect pg data in the root of svc_data_path, where older versions of this plan had it
if [[ -f "{{pkg.svc_data_path}}/PG_VERSION" ]]; then
  echo "PGDATA detected in the root of the data path ( {{pkg.svc_data_path}} ), relocating it to {{pkg.svc_data_path}}/pgdata"
  mkdir -p {{pkg.svc_data_path}}/pgdata
  # bash extended globbing can cleanly move everything under a subfolder http://www.linuxjournal.com/content/bash-extended-globbing
  mv {{pkg.svc_data_path}}/!(pgdata) {{pkg.svc_data_path}}/pgdata/
  chmod 0700 {{pkg.svc_data_path}}/pgdata
else
  mkdir -p {{pkg.svc_data_path}}/pgdata
fi

mkdir -p {{pkg.svc_data_path}}/archive
init_pgpass
ensure_dir_ownership

{{#unless svc.me.follower ~}}
if [[ ! -f "{{pkg.svc_data_path}}/pgdata/PG_VERSION" ]]; then
  echo " Database does not exist, creating with 'initdb'"
    initdb -U {{cfg.superuser.name}} \
    -E utf8 \
    -D {{pkg.svc_data_path}}/pgdata \
    --pwfile {{pkg.svc_config_path}}/pwfile \
    --locale POSIX \
    --data-checksums
fi
{{~/unless}}
{{#if svc.me.follower ~}}
setup_replication_user_in_master
if [ $? != 0 ]; then
  echo 'Waiting for leader to become available before initializing'
  exit 1
fi
{{~/if}}
