#!/bin/bash -xe

exec 2>&1

{{#if cfg.nomad.agent}}
exec dockerd &
exec nomad agent -config {{pkg.svc_config_path}}/settings.hcl
{{/if ~}}

su hab -c "exec nomad agent -config {{pkg.svc_config_path}}/settings.hcl"

