#!/bin/bash

exec 2>&1

#{{#if cfg.runtime.cassandra_java_opts}}
#   JVM_OPTS -- Additional arguments to the JVM for heap size, etc
#{{/if ~}}
export JAVA_HOME="$(hab pkg path core/jre8)"
export CASSANDRA_CONF="file://{{pkg.svc_config_path}}"

exec cassandra -f \
	-Dcassandra.logdir="{{pkg.svc_var_path}}/logs"
