#!/bin/sh
#

mkdir -p {{pkg.svc_data_path}}/htdocs
mkdir -p {{pkg.svc_data_path}}/cgi-bin
mkdir -p {{pkg.svc_var_path}}/logs

if [ ! -d {{pkg.path}}/modules ]; then
	cp -f -r $(hab pkg path core/httpd)/modules {{pkg.path}}/
fi

if [ ! -d {{pkg.path}}/conf ]; then
	cp -f -r $(hab pkg path core/httpd)/conf {{pkg.path}}/
fi

if [ ! -d {{pkg.path}}/logs ]; then
	cp -f -r $(hab pkg path core/httpd)/logs {{pkg.path}}/
fi
