#!/bin/sh
#

mkdir -p {{pkg.svc_data_path}}/htdocs
mkdir -p {{pkg.svc_data_path}}/cgi-bin
mkdir -p {{pkg.svc_var_path}}/logs

find {{pkg.svc_data_path}} -type d -exec chmod 0755 {} \;
find {{pkg.svc_data_path}} -type f -exec chmod 0644 {} \;
