#!{{pkgPathFor "core/bash"}}/bin/bash

# httpd starts as root but then drops privileges to the "hab" user. This makes
# it so the server doesn't have to run as root the whole time and is the
# correct behavior. However, this means that all of the `pkg_svc_*` paths will
# get changed to root:root mode 0700 after every reconfigure. This script will
# make sure things get changed to being owned by hab:hab whenver that happens.
chown -R hab:hab "{{pkg.svc_config_path}}" \
  "{{pkg.svc_data_path}}" \
  "{{pkg.svc_files_path}}" \
  "{{pkg.svc_static_path}}" \
  "{{pkg.svc_var_path}}"
