#!/bin/bash

exec 2>&1

## Setup database connection
mysql_ready() {
  mysqladmin ping -h {{bind.database.first.sys.ip}} -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} > /dev/null 2>&1
}

if !(mysql_ready) then
  echo "Waiting for MySQL..."
  exit 1
fi

mysql -h {{bind.database.first.sys.ip}} -u {{bind.database.first.cfg.username}} -p{{bind.database.first.cfg.password}} -e "create database IF NOT EXISTS {{cfg.database_name}}"

## Place Drupal PHP sources into the correct location
cp -r {{pkg.path}}/drupal/* {{pkg.svc_data_path}}/
chmod +x {{pkg/svc_data_path}}
chown -RL hab:hab {{pkg.svc_data_path}}
