[rabbitmq]
# Host on which to listen. An empty string means "listen on all interfaces."
listen_host=""

# Port to bind to.
listen_port=5672

# Virtual host to create when RabbitMQ creates a new database from scratch. The
# exchange amq.rabbitmq.log will exist in this virtual host.
default_vhost="/"

# User name to create when RabbitMQ creates a new database from scratch.
default_user="admin"

# Password for the default user.
default_pass="admin"

# give our default user the proper permissions
default_user_tags = ["administrator", "management"]

cluster_with=""
name="rabbit"
ram=false

[rabbitmq.management]

# Whether to enable the rabbitmq management plugin.
enabled=true

[erlang]
cookie="Gm0+QGpGcsEcxjJPEBY/Tg=="
