[rabbitmq]

# Host on which to listen. An empty string means "listen on all interfaces."
listen_host=""

# Port to bind to.
listen_port=5672

# Virtual host to create when RabbitMQ creates a new database from scratch. The
# exchange amq.rabbitmq.log will exist in this virtual host.
default_vhost="/"

# User name to create when RabbitMQ creates a new database from scratch.
default_user="guest"

# Password for the default user.
default_pass="guest"

# Install a special supervisor in docker to reap zomblie child processes
docker_supervision=false

[rabbitmq.management]
# Whether to enable the rabbitmq management plugin.
enabled=false

[erlang]
cookie=false

[rabbitmq.cluster]
enabled=false
