### Default config

# run_as accepts a string of supervisor, nimbus or ui
run_as = "nimbus"

java-library-path = "/usr/local/lib:/opt/local/lib:/usr/lib"
logs-users = "null"
dev-zookeeper-path = "/tmp/dev-storm-zookeeper"
client-blobstore-class = "org.apache.storm.blobstore.NimbusBlobStore"

#default storm daemon metrics reporter plugins
storm-daemon-metrics-reporter-plugins = ["org.apache.storm.daemon.metrics.reporters.JmxPreparableReporter"]

# configuration of cluster metrics consumer
storm-cluster-metrics-consumer-publish-interval-secs = 60

# Default plugin to use for automatic network topology discovery
storm-network-topography-plugin = "org.apache.storm.networktopography.DefaultRackDNSToSwitchMapping"

# default number of seconds group mapping service will cache user group
storm-group-mapping-service-cache-duration-secs = 120

resource-aware-scheduler-eviction-strategy = "org.apache.storm.scheduler.resource.strategies.eviction.DefaultEvictionStrategy"
resource-aware-scheduler-priority-strategy = "org.apache.storm.scheduler.resource.strategies.priority.DefaultSchedulingPriorityStrategy"

# now should be "null" by default
topology-backpressure-enable = false
backpressure-disruptor-high-watermark = 0.9
backpressure-disruptor-low-watermark = 0.4

scheduler-display-resource = false
topology-min-replication-count = 1
topology-max-replication-wait-time-sec = 60

### nimbus.* configs are for the master
### Specific config for nimbus
[nimbus]
childopts = "-Xmx1024m"
task-timeout-secs = 30
supervisor-timeout-secs = 60
monitor-freq-secs = 10
cleanup-inbox-freq-secs = 600
inbox-jar-expiration-secs = 3600
code-sync-freq-secs = 120
task-launch-secs = 120
file-copy-expiration-secs = 600
topology-validator = "org.apache.storm.nimbus.DefaultTopologyValidator"

credential-renewers-freq-secs = 600
queue-size = 100000

[nimbus.thrift]
port = 6627
threads = 64
max_buffer_size = 1048576

[nimbus.blobstore]
class = "org.apache.storm.blobstore.LocalFsBlobStore"
expiration-secs = 600


[supervisor]
## blobstore configs
childopts = "-Xmx256m"
run-worker-as-user = false
#how frequently the supervisor checks on the status of the processes it's monitoring and restarts if necessary
monitor-frequency-secs = 3
#how frequently the supervisor heartbeats to the cluster state (for nimbus)
heartbeat-frequency-secs = 5
enable = true
supervisors = []
supervisors-commands = []
memory-capacity-mb = 3072.0
#By convention 1 cpu core should be about 100, but this can be adjusted if needed
# using 100 makes it simple to set the desired value to the capacity measurement
# for single threaded bolts
cpu-capacity = 400.0

[supervisor.worker]
#how long supervisor will wait to ensure that a worker process is started
start-timeout-secs = 120
#how long between heartbeats until supervisor considers that worker dead and tries to restart it
timeout-secs = 30
#how many seconds to sleep for before shutting down threads on worker
shutdown-sleep-secs = 3

[supervisor.blobstore]
class = "org.apache.storm.blobstore.NimbusBlobStore"
download-thread-count = 5
download-max_retries = 3

[supervisor.localizer]
cache-target-size-mb = 10240
cleanup-interval-ms = 600000


[worker]
ports = [6700, 6701, 6702, 6703]
### worker.* configs are for task workers
heap-memory-mb = 768
childopts = "-Xmx%HEAP-MEM%m -XX:+PrintGCDetails -Xloggc:artifacts/gc.log -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=1M -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=artifacts/heapdump"
gc-childopts = ""

# Unlocking commercial features requires a special license from Oracle.
# See http://www.oracle.com/technetwork/java/javase/terms/products/index.html
# For this reason, profiler features are disabled by default.
profiler-enabled = false
profiler-childopts = "-XX:+UnlockCommercialFeatures -XX:+FlightRecorder"
profiler-command = "flight.bash"
heartbeat-frequency-secs = 1

# check whether dynamic log levels can be reset from DEBUG to INFO in workers
log-level-reset-poll-secs = 30


[ui]
host = "0.0.0.0"
port = 8080
childopts = "-Xmx768m"
actions-enabled = true
filter = "null"
filter-params = "null"
users = "null"
header-buffer-bytes = 4096
http-creds-plugin = "org.apache.storm.security.auth.DefaultHttpCredentialsPlugin"
http-x-frame-options = "DENY"


[storm]
### storm.* configs are general configurations
# the local dir is where jars are kept
# local-dir = "storm-local"
log4j2-conf-dir = "log4j2"

exhibitor-port = 8080
exhibitor-poll-uripath = "/exhibitor/v1/cluster/list"
cluster-mode = "distributed" # can be distributed or local
local-mode-zmq = false
thrift-transport = "org.apache.storm.security.auth.SimpleTransportPlugin"
thrift-socket-timeout-ms = 600000
principal-tolocal = "org.apache.storm.security.auth.DefaultPrincipalToLocal"
group-mapping-service = "org.apache.storm.security.auth.ShellBasedGroupsMapping"
group-mapping-service-params = "null"
messaging-transport = "org.apache.storm.messaging.netty.Context"
nimbus-retry-times = 5
nimbus-retry-interval-millis = 2000
nimbus-retry-intervalceiling-millis = 60000
auth-simple-white-list-users = []
auth-simple-acl-users = []
auth-simple-acl-users-commands = []
auth-simple-acl-admins = []
cluster-state-store = "org.apache.storm.cluster_state.zookeeper_state_factory"
meta-serialization-delegate = "org.apache.storm.serialization.GzipThriftSerializationDelegate"
codedistributor-class = "org.apache.storm.codedistributor.LocalFileSystemCodeDistributor"
workers-artifacts-dir = "workers-artifacts"
health-check-dir = "healthchecks"
health-check-timeout-ms = 5000
disable-symlinks = false

[storm.zookeeper]
port = 2181
root = "/storm"
session-timeout = 20000
connection-timeout = 15000
retry-times = 5
retry-interval = 1000
retry-intervalceiling-millis = 30000
auth-user = "null"
auth-password = "null"

[storm.blobstore]
inputstream-buffer-size-bytes = 65536
replication-factor = 3
# For secure mode we would want to change this config to true
acl-validation-enabled = false

[storm.messaging.netty]
server_worker_threads = 1
client_worker_threads = 1
buffer_size = 5242880 #5MB buffer
# Since nimbus.task.launch.secs and supervisor.worker.start.timeout.secs are 120, other workers should also wait at least that long before giving up on connecting to the other worker. The reconnection period need also be bigger than storm.zookeeper.session.timeout(default is 20s), so that we can abort the reconnection when the target worker is dead.
max_retries = 300
max_wait_ms = 1000
min_wait_ms = 100

# If the Netty messaging layer is busy(netty internal buffer not writable), the Netty client will try to batch message as more as possible up to the size of storm.messaging.netty.transfer.batch.size bytes, otherwise it will try to flush message as soon as possible to reduce latency.
transfer-batch-size = 262144
# Sets the backlog value to specify when the channel binds to a local address
socket-backlog = 500

# By default, the Netty SASL authentication is set to false.  Users can override and set it true for a specific topology.
authentication = false

[logviewer]
port = 8000
childopts = "-Xmx128m"
cleanup-age-mins = 10080
appender-name = "A1"
max-sum-worker-logs-size-mb = 4096
max-per-worker-logs-size-mb = 2048

[drpc]
port = 3772
worker-threads = 64
max_buffer_size = 1048576
queue-size = 128
invocations-port = 3773
invocations-threads = 64
request-timeout-secs = 600
childopts = "-Xmx768m"
http-port = 3774
https-port = -1
https-keystore-password = ""
https-keystore-type = "JKS"
http-creds-plugin = "org.apache.storm.security.auth.DefaultHttpCredentialsPlugin"
authorizer-acl-filename = "drpc-auth-acl.yaml"
authorizer-acl-strict = false

[transactional]
zookeeper-root = "/transactional"
zookeeper-servers = "null"
zookeeper-port = "null"



[task]
heartbeat-frequency-secs = 3
refresh-poll-secs = 10
credentials-poll-secs = 30
backpressure-poll-secs = 30

[zmq]
threads = 1
linger-millis = 5000
hwm = 0



[topology]
### topology.* configs are for specific executing storms
enable-message-timeouts = true
debug = false
workers = 1
acker-executors = "null"
eventlogger-executors = 0
tasks = "null"
# maximum amount of time a message has to complete before it's considered failed
message-timeout-secs = 30
multilang-serializer = "org.apache.storm.multilang.JsonSerializer"
shellbolt-max-pending = 100
skip-missing-kryo-registrations = false
max-task-parallelism = "null"
max-spout-pending = "null"
state-synchronization-timeout-secs = 60
stats-sample-rate = 0.05
builtin-metrics-bucket-size-secs = 60
fall-back-on-java-serialization = true
worker-childopts = "null"
worker-logwriter-childopts = "-Xmx64m"
executor-receive-buffer-size = 1024 #batched
executor-send-buffer-size = 1024 #individual messages
transfer-buffer-size = 1024 # batched
tick-tuple-freq-secs = "null"
worker-shared-thread-pool-size = 4
spout-wait-strategy = "org.apache.storm.spout.SleepSpoutWaitStrategy"
sleep-spout-wait-strategy-time-ms = 1
error-throttle-interval-secs = 10
max-error-report-per-interval = 5
kryo-factory = "org.apache.storm.serialization.DefaultKryoFactory"
tuple-serializer = "org.apache.storm.serialization.types.ListDelegateSerializer"
trident-batch-emit-interval-millis = 500
testing-always-try-serialize = false
classpath = "null"
environment = "null"
bolts-outgoing-overflow-buffer-enable = false
disruptor-wait-timeout-millis = 1000
disruptor-batch-size = 100
disruptor-batch-timeout-millis = 1
disable-loadaware-messaging = false
state-checkpoint-interval-ms = 1000

# Configs for Resource Aware Scheduler
# topology priority describing the importance of the topology in decreasing importance starting from 0 (i.e. 0 is the highest priority and the priority importance decreases as the priority number increases).
# Recommended range of 0-29 but no hard limit set.
priority = 29
component-resources-onheap-memory-mb = 128.0
component-resources-offheap-memory-mb = 0.0
component-cpu-pcore-percent = 10.0
worker-max-heap-size-mb = 768.0

scheduler-strategy = "org.apache.storm.scheduler.resource.strategies.scheduling.DefaultResourceAwareStrategy"

# control how many worker receiver threads we need per worker
worker-receiver-thread-count = 1


[pacemaker]
host = "localhost"
port = 6699
base-threads = 10
max-threads = 50
thread-timeout = 10
childopts = "-Xmx1024m"
auth-method = "NONE"
kerberos-users = []
