pkg_name=linux-pam
pkg_origin=core
pkg_version=1.3.0
pkg_license=('BSD-3-Clause' 'GPL')
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_description="Linux-PAM is a free implementation of the following DCE-RFC from Sunsoft."
pkg_upstream_url="http://www.linux-pam.org/"
pkg_source=http://www.linux-pam.org/library/Linux-PAM-${pkg_version}.tar.bz2
pkg_filename=${pkg_name}-${pkg_version}.tar.bz2
pkg_dirname=Linux-PAM-${pkg_version}
pkg_shasum=241aed1ef522f66ed672719ecf2205ec513fd0075ed80cda8e086a5b1a01d1bb
pkg_deps=(core/glibc)
pkg_build_deps=(core/coreutils core/gcc core/make)
pkg_bin_dirs=(sbin)
pkg_include_dirs=(include)
pkg_lib_dirs=(lib)
