[mongod]

[mongod.system_log]
verbosity = 0
quiet = false
trace_all_exceptions = true
syslog_facility = "user"
log_append = true
log_rotate = "rename"
destination = "file"
time_stamp_format = "iso8601-local"

	[mongod.system_log.component]

		[mongod.system_log.component.access_control]
		verbosity = 0

		[mongod.system_log.component.command]
		verbosity = 0

		[mongod.system_log.component.control]
		verbosity = 0

		[mongod.system_log.component.ftdc]
		verbosity = 0

		[mongod.system_log.component.geo]
		verbosity = 0

		[mongod.system_log.component.index]
		verbosity = 0

		[mongod.system_log.component.network]
		verbosity = 0

		[mongod.system_log.component.query]
		verbosity = 0

		[mongod.system_log.component.replication]
		verbosity = 0

		[mongod.system_log.component.sharding]
		verbosity = 0

		[mongod.system_log.component.storage]
		verbosity = 0

			[mongod.system_log.component.storage.journal]
			verbosity = 0

		[mongod.system_log.component.write]
		verbosity = 0

[mongod.process_management]
fork = false
pid_file_path = ""

[mongod.net]
port = 27017
bind_ip = "127.0.0.1"
max_incoming_connections = 65536
wire_object_check = true
ipv6 = false

	[mongod.net.unix_domain_socket]
	enabled = true
	file_permissions = "0700"

	#warning may produce vulnerabilties to server if enabled
	[mongod.net.http]
	enabled = false
	jsonp_enabled = false
	rest_interface_enabled = false

	[mongod.net.ssl]
	enabled = false
	mode = "disabled"
	pem_key_file = ""
	pem_key_password = ""
	cluster_file = ""
	cluster_password = ""
	ca_file = ""
	crl_file = ""
	allow_connections_without_certificates = false
	allow_invalid_certificates = false
	allow_invalid_hostnames = false
	disabled_protocols = ""

[mongod.security]
key_file = ""
cluster_auth_mode = "keyFile"
authorization = "disabled"
javascript_enabled = true

	[mongod.security.sasl]
	enabled = false
	host_name = ""
	sasl_authd_socket_path = ""

[mongod.storage]
index_build_retry = true
repair_path = ""
directory_per_db = false
sync_period_secs = 60
engine = "wiredTiger"

	[mongod.storage.journal]
	enabled = true
	commit_intervals = 100

	[mongod.storage.mmapv1]
	prealloc_data_files = true
	ns_size = 16
	small_files = false

		[mongod.storage.mmapv1.quota]
		enforced = false
		max_files_per_db = 8

		[mongod.storage.mmapv1.journal]
		debug_flags = 0

	[mongod.storage.wired_tiger]

		[mongod.storage.wired_tiger.engine_config]
		new_cache = false
		cache_size_gb = 1
		journal_compressor = "snappy"
		directory_for_indexes = false

		[mongod.storage.wired_tiger.collection_config]
		block_compressor = "snappy"

		[mongod.storage.wired_tiger.index_config]
		prefix_compression = true

[mongod.operation_profiling]
slow_op_threshold = 100
mode = "off"

[mongod.replication]
new_oplog_size = false
oplog_size_mb = 100
repl_set_name = ""
secondary_prefix_prefetch = "all"
enable_majority_read_concern = false

[mongod.sharding]
cluster_role = ""
archive_moved_chunks = false

[mongod.snmp]
enabled = false
subagent = false
master = false


[mongos]

[mongos.system_log]
verbosity = 0
quiet = false
trace_all_exceptions = true
syslog_facility = "user"
log_append = true
log_rotate = "rename"
destination = ""
time_stamp_format = "iso8601-local"

	[mongos.system_log.component]

		[mongos.system_log.component.access_control]
		verbosity = 0

		[mongos.system_log.component.command]
		verbosity = 0

		[mongos.system_log.component.control]
		verbosity = 0

		[mongos.system_log.component.ftdc]
		verbosity = 0

		[mongos.system_log.component.geo]
		verbosity = 0

		[mongos.system_log.component.index]
		verbosity = 0

		[mongos.system_log.component.network]
		verbosity = 0

		[mongos.system_log.component.query]
		verbosity = 0

		[mongos.system_log.component.replication]
		verbosity = 0

		[mongos.system_log.component.sharding]
		verbosity = 0

		[mongos.system_log.component.storage]
		verbosity = 0

			[mongos.system_log.component.storage.journal]
			verbosity = 0

		[mongos.system_log.component.write]
		verbosity = 0

[mongos.process_management]
fork = false
pid_file_path = ""

[mongos.net]
port = 27017
bind_ip = "127.0.0.1"
max_incoming_connections = 65536
wire_object_check = true
ipv6 = false

	[mongos.net.unix_domain_socket]
	enabled = true
	file_permissions = "0700"

	#warning may produce vulnerabilties to server if enabled
	[mongos.net.http]
	enabled = false

	[mongos.net.ssl]
	mode = "disabled"
	pem_key_file = ""
	pem_key_password = ""
	cluster_file = ""
	cluster_password = ""
	ca_file = ""
	crl_file = ""
	allow_connections_without_certificates = false
	allow_invalid_certificates = false
	allow_invalid_hostnames = false
	disabled_protocols = ""

[mongos.security]
key_file = ""
cluster_auth_mode = "keyFile"
javascript_enabled = true

	[mongos.security.sasl]
	enabled = false
	host_name = ""
	sasl_authd_socket_path = ""

[mongos.storage]
engine = "wiredTiger"

	[mongos.storage.wired_tiger]

		[mongos.storage.wired_tiger.engine_config]
		cache_size_gb = 1
		journal_compressor = "snappy"
		directory_for_indexes = false

		[mongos.storage.wired_tiger.collection_config]
		block_compressor = "snappy"

		[mongos.storage.wired_tiger.index_config]
		prefix_compression = true

[mongos.replication]
enable_majority_read_concern = false
local_ping_threshold = 15

[mongos.sharding]
archive_moved_chunks = false
auto_split = true
config_db = ""
chunk_size = 64
configsvr_mode = ""
