#!/bin/bash

exec 2>&1

export ZOOBINDIR="{{pkg.path}}/bin/"
export ZOOCFGDIR="{{pkg.svc_config_path}}"
export JAVA_HOME="{{pkgPathFor "core/jre8"}}"

{{pkg.path}}/bin/zkEnv.sh

exec {{pkg.path}}/bin/zkServer.sh start-foreground
