pkg_name=libxslt
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_description="Libxslt is the XSLT C library developed for the GNOME project"
pkg_upstream_url=http://xmlsoft.org/XSLT/
pkg_version=1.1.33
pkg_origin=core
pkg_license=('libxslt')
pkg_source=http://xmlsoft.org/sources/libxslt-${pkg_version}.tar.gz
pkg_filename=libxslt-${pkg_version}.tar.gz
pkg_shasum=8e36605144409df979cab43d835002f63988f3dc94d5d3537c12796db90e38c8
pkg_deps=(core/glibc core/libxml2 core/zlib)
pkg_build_deps=(core/coreutils core/patch core/make core/gcc)
pkg_bin_dirs=(bin)
pkg_lib_dirs=(lib)
pkg_include_dirs=(include)
