pkg_name=libxslt
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_description="Libxslt is the XSLT C library developed for the GNOME project"
pkg_upstream_url=http://xmlsoft.org/XSLT/
pkg_version=1.1.31
pkg_origin=core
pkg_license=('libxslt')
pkg_source=http://xmlsoft.org/sources/${pkg_name}-${pkg_version}.tar.gz
pkg_filename=${pkg_name}-${pkg_version}.tar.gz
pkg_shasum=db25e96b6b801144277e67c05b10560ac09dfff82ccd53a154ce86e43622f3ab
pkg_deps=(core/glibc core/libxml2 core/zlib)
pkg_build_deps=(core/coreutils core/patch core/make core/gcc)
pkg_bin_dirs=(bin)
pkg_lib_dirs=(lib)
pkg_include_dirs=(include)
