pkg_name=libxslt
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_description="Libxslt is the XSLT C library developed for the GNOME project"
pkg_upstream_url=http://xmlsoft.org/XSLT/
pkg_version=1.1.42
pkg_origin=core
pkg_license=('libxslt')
pkg_source=https://download.gnome.org/sources/libxslt/1.1/libxslt-${pkg_version}.tar.xz
pkg_filename=libxslt-${pkg_version}.tar.gz
pkg_shasum=85ca62cac0d41fc77d3f6033da9df6fd73d20ea2fc18b0a3609ffb4110e1baeb
pkg_deps=(core/glibc core/libxml2 core/zlib)
pkg_build_deps=(core/coreutils core/patch core/make core/gcc core/pkg-config core/python)
pkg_bin_dirs=(bin)
pkg_lib_dirs=(lib)
pkg_include_dirs=(include)
