maxconn = 32
httpchk = "GET /"

[front-end]
listen = "*"
port = 80
mode = "http"

[status]
enabled = false
listen = "*"
port = 9000
user = "admin"
password = "password"
uri = "/haproxy-stats"

[[server]]
name = "first"
host_or_ip = "172.17.0.3"
port = "8000"

[[server]]
name = "second"
host_or_ip = "172.17.0.4"
port = "8000"
