maxconn = 32
mode = "http"
bind = "*:80"
stats_enabled = false
stats_password = ""
stats_realm = "haproxy_stats"
stats_uri = "/haproxy_stats"
stats_user = ""

[[server]]
name = "first"
host_or_ip = "172.17.0.3"
port = "8000"

[[server]]
name = "second"
host_or_ip = "172.17.0.4"
port = "8000"
