rootLogger: {{cfg.logger.level}}, console, file

logger:
  action: {{cfg.logger.action}}

# indices.recovery: {{cfg.logger.indices.recovery}}

# discovery: {{cfg.logger.discovery}}

deprecation.discovery: {{cfg.logger.deprecation.discovery}}

com.amazonaws: {{cfg.logger.com.amazonaws}}

appender:
  console:
    type: {{cfg.logger.appender.console.type}}
    layout:
      type: {{cfg.logger.appender.console.layout.type}}
      conversionPattern: {{cfg.logger.appender.console.layout.conversionPattern}}

  file:
    type: {{cfg.logger.appender.file.type}}
    file: {{cfg.logger.appender.file.file}}
    datePattern: {{cfg.logger.appender.file.datePattern}}
    layout:
      type: {{cfg.logger.appender.file.layout.type}}
      conversionPattern: {{cfg.logger.appender.file.layout.conversionPattern}}