#!/bin/bash

exec 2>&1

export JAVA_HOME="$(hab pkg path core/jre8)"
export KAFKA_LOG4J_OPTS="-Dlog4j.configuration=file:{{pkg.svc_config_path}}/log4j.properties"
export EXTRA_ARGS="-name kafkaServer"

exec {{pkg.path}}/bin/kafka-server-start.sh "{{pkg.svc_config_path}}/server.properties"
