 #    #   ####      #    #    #  #    #
 ##   #  #    #     #    ##   #   #  #
 # #  #  #          #    # #  #    ##
 #  # #  #  ###     #    #  # #    ##
 #   ##  #    #     #    #   ##   #  #
 #    #   ####      #    #    #  #    #
 # For help with NGINX Config Tuning,
 # refer to: http://nginx.org/en/docs/http/ngx_http_core_module.html



#### General Configuration
# redirector: If set, bypass normal config and just redirect http to https
redirector = false

# worker_processes: Number of NGINX processes. Default = 1
worker_processes = 4



#### Events Context Configuration
[events]
# worker_connections: Connections per Worker Process.  Default = 1024
worker_connections = 1024


#### HTTP Context Configuration
[http]
# http.sendfile: Enable (on) or disable (off) Sendfile Support.  Default = on
sendfile = "on"

# http.tcp_nopush: Enable (on) or disable (off) use of TCP_NOPUSH or TCP_CORK socket option. Default = on
tcp_nopush = "on"

# http.tcp_nodelay: Enable (on) or disable (off) use of the TCP_NODELAY option. Default = on
tcp_nodelay = "on"

# http.keepalive_timeout: Timeout on client connection keepalive, in seconds. Default = 75
keepalive_timeout = 60

extra_config = ""

[http.server]
name = "localhost"
canonicalize = false
extra_config = ""

[http.server.default_location]
root = ""
index = "index.html index.htm"
extra_config = ""

[http.server.ssl]
enable = false
port = 443
certificate = ""
certificate_file = "/hab/svc/nginx/files/ssl.crt"
key = ""
key_file = "/hab/svc/nginx/files/ssl.key"
protocols = "TLSv1 TLSv1.1 TLSv1.2"

[http.listen]
port = 80
