#!{{pkgPathFor "core/bash"}}/bin/bash

source {{pkg.svc_config_path}}/functions.sh

init_pgpass

{{ #unless svc.me.follower }}
if [ -f {{pkg.svc_data_path}}/recovery.conf ]; then
  echo "Promoting database"
  until pg_isready -U {{cfg.superuser.name}} -h localhost -p {{cfg.port}}; do
    echo "Waiting for database to start"
    sleep 1
  done

  chpst -U hab:hab -u hab:hab pg_ctl promote -D {{pkg.svc_data_path}}
fi

{{~/unless}}
