###################################################
# Tunable OpenVPN configuration. Lifted in part from
# https://openvpn.net/index.php/open-source/documentation/howto.html#examples
###################################################

# Which local IP address should OpenVPN
# listen on? (optional)
# Binds to all interfaces by default
# local    = "0.0.0.0"

# Specify which auth method to use, set to false to exclude this option.
# auth = false
auth = "SHA256"

# Which TCP/UDP port should OpenVPN listen on? If you want to run
# multiple OpenVPN instances on the same machine, use a different port
# number for each one. You will need to open up this port on your
# firewall.
port = 1194

# TCP or UDP server?
proto = "udp"

# "dev tun" will create a routed IP tunnel,
# "dev tap" will create an ethernet tunnel.
dev = "tun"

# Network topology
# Should be subnet (addressing via IP)
# unless Windows clients v2.0.9 and lower have to
# be supported (then net30, i.e. a /30 per client)
# Defaults to net30 (not recommended)
topology = "subnet"

# Non-Windows systems usually don't need this.
dev-node = false

# SSL/TLS root certificate (ca), certificate (cert), and private key
# (key). Each client and the server must have their own cert and key
# file. The server and all clients will use the same ca file.
#
# Any X509 key management system can be used.
# OpenVPN can also use a PKCS #12 formatted key file
# (see "pkcs12" directive in man page).

# To specify the SSL Certificate files:
# ca-file = "/hab/svc/openvpn/files/ca.crt"
# cert-file = "/hab/svc/openvpn/files/server.crt"
# key-file = "/hab/svc/openvpn/files/server.key"

# To intject the SSL Certificates directly into the config
# ca = """
# ---- BEGIN CERT ----
# CERT HERE
# ---- END CERT ----
# """
# cert = """
# """
# key = """
# """"

# Diffie hellman parameters.
# Generate your own with:
#
#   openssl dhparam -out dh.pem 2048
#
# dh-file = "/hab/svc/openvpn/files/dh.pem"
# dh = """
# """

# Configure server mode and supply a VPN subnet for OpenVPN to draw
# client addresses from. The server will take 10.8.0.1 for itself, the
# rest will be made available to clients. Each client will be able to
# reach the server on 10.8.0.1. Comment this line out if you are
# ethernet bridging. See the man page for more info.
server = "10.8.0.0 255.255.255.0"

# To assign specific IP addresses to specific
# clients or if a connecting client has a private
# subnet behind it that should also have VPN access,
# use the subdirectory "ccd" for client-specific
# configuration files (see man page for more info).
#
# To create route statements they can be added as an array
# route = ["192.168.0.0 255.255.255.0"]

# Maintain a record of client virtual IP address associations in this
# file. If OpenVPN goes down or is restarted, reconnecting clients can
# be assigned the same virtual IP address from the pool that was
# previously assigned.
#
# defaults to openvpn data directory
# ifconfig-pool-persist-file = "/hab/svc/openvpn/data/ipp.txt"

ifconfig-pool-persist = "true"

# Configure server mode for ethernet bridging. You must first use your
# OS's bridging capability to bridge the TAP interface with the
# ethernet NIC interface. Then you must manually set the IP/netmask on
# the bridge interface, here we assume 10.8.0.4/255.255.255.0. Finally
# we must set aside an IP range in this subnet (start=10.8.0.50
# end=10.8.0.100) to allocate to connecting clients. Leave this line
# commented out unless you are ethernet bridging.
#
# for example:
#server-bridge = "10.8.0.4 255.255.255.0 10.8.0.50 10.8.0.100"
server-bridge = false

# Push routes to the client to allow it to reach other private subnets
# behind the server. Remember that these private subnets will also
# need to know to route the OpenVPN client address pool
# (10.8.0.0/255.255.255.0) back to the OpenVPN server.
#
# Push is an array because there's a variety of options that can be
# specified in the OpenVPN server config. See the OpenVPN
# documentation for more options.
# push = ["route 192.168.10.0 255.255.255.0"]

# Override the default client-config-dir setting
# client-config-dir = /hab/svc/openvpn/data/ccd

# Suppose that you want to enable different firewall access policies
# for different groups of clients. There are two methods:
#
# (1) Run multiple OpenVPN daemons, one for each
#     group, and firewall the TUN/TAP interface
#     for each group/daemon appropriately.
#
# (2) (Advanced) Create a script to dynamically
#     modify the firewall in response to access
#     from different clients.  See man
#     page for more info on learn-address script.
#
#learn-address = "./script"
learn-address = false

# Set this directive to true to allow different clients to be able to
# "see" each other. By default, clients will only see the server. To
# force clients to only see the server, you will also need to
# appropriately firewall the server's TUN/TAP interface.

client-to-client = false

# Uncomment this directive if multiple clients might connect with the
# same certificate/key files or common names. This is recommended only
# for testing purposes. For production use, each client should have
# its own certificate/key pair.
#
# IF YOU HAVE NOT GENERATED INDIVIDUAL CERTIFICATE/KEY PAIRS FOR EACH
# CLIENT, EACH HAVING ITS OWN UNIQUE "COMMON NAME", UNCOMMENT THIS
# LINE OUT.
duplicate-cn = false

# The keepalive directive causes ping-like
# messages to be sent back and forth over
# the link so that each side knows when
# the other side has gone down.
# Ping every 10 seconds, assume that remote
# peer is down if no ping received during
# a 120 second time period.
keepalive = "10 120"

# For extra security beyond that provided
# by SSL/TLS, create an "HMAC firewall"
# to help block DoS attacks and UDP port flooding.
#
# Generate with:
#   openvpn --genkey --secret ta.key
#
# The server and each client must have
# a copy of this key.
#
# for example:
# tls-auth = true
# tls-auth-file = "/hab/svc/openvpn/files/ta.key"
# or
# tls-auth-cert = """
# """

tls-auth = false

# Select a cryptographic cipher.
# This config item must be copied to
# the client config file as well.
# Other valid values:
#     AES-128-CBC, DES-EDE3-CBC
cipher = "BF-CBC"

# Enable compression on the VPN link and push the
# option to the client (v2.4+ only, for earlier
# versions see below)
compress = "lz4-v2"

# For compression compatible with older clients use comp-lzo
# If you enable it here, you must also
# enable it in the client config file.
comp-lzo = false

# The maximum number of concurrently connected
# clients we want to allow.
max-clients = 100

# It's a good idea to reduce the OpenVPN
# daemon's privileges after initialization.
user = "hab"
group = "hab"

# The persist options will try to avoid
# accessing certain resources on restart
# that may no longer be accessible because
# of the privilege downgrade.
persist-key = true
persist-tun = true

# Output a short status file showing
# current connections, truncated
# and rewritten every minute.
#
# Uncomment to override the default:
# status-file = "/hab/svc/openvpn/data/openvpn-status.log"

status = true

# By default, log messages will go to the syslog (or
# on Windows, if running as a service, they will go to
# the "\Program Files\OpenVPN\log" directory).
# Use log or log-append to override this default.
# "log" will truncate the log file on OpenVPN startup,
# while "log-append" will append to it.  Use one
# or the other (but not both).
# log-file = "/hab/svc/openvpn/var/log/openvpn.log"
# log-append-file = "/hab/svc/openvpn/var/log/openvpn.log"

log-to-syslog = true

# Set the appropriate level of log
# file verbosity.
#
# 0 is silent, except for fatal errors
# 4 is reasonable for general usage
# 5 and 6 can help to debug connection problems
# 9 is extremely verbose
verb = 3

# Silence repeating messages.  At most 20
# sequential messages of the same message
# category will be output to the log.
mute = 20

# Notify the client that when the server restarts so it
# can automatically reconnect.
explicit-exit-notify = true
