#!/bin/sh

{{~#if cfg.jenkins.http.enabled}}
CHECK_ADDR="{{sys.ip}}:{{cfg.jenkins.http.port}}"
{{~/if}}
{{~#if cfg.jenkins.https.enabled}}
CHECK_ADDR="{{sys.ip}}:{{cfg.jenkins.https.port}}"
{{~/if}}
{{~#if cfg.jenkins.http2.enabled}}
CHECK_ADDR="{{sys.ip}}:{{cfg.jenkins.http2.port}}"
{{~/if}}

#curl jenkins login page - 200 code is "ok"
STATUS="$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' ${CHECK_ADDR}/login)"

case $STATUS in
  200)
    rc=0 ;;
  1)
    rc=1 ;;
  2)
    rc=2 ;;
  *)
    rc=3 ;;
esac

# hab error codes
# 0- ok
# 1- warning
# 2- critical
# 3- unknown

exit $rc
