pkg_name=sshpass
pkg_origin=core
pkg_version="1.09"
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_license=("GPL-2.0-or-later")
pkg_filename="${pkg_name}-${pkg_version}.tar.gz"
pkg_source="https://downloads.sourceforge.net/project/${pkg_name}/${pkg_name}/${pkg_version}/${pkg_filename}"
pkg_shasum="cd4c34bc13e42618f751a4f1e660f15cc1f859d2b518d725e9a822bc9de8c943"
pkg_build_deps=(core/make core/gcc)
pkg_bin_dirs=(bin)
pkg_description="Non-interactive ssh password auth"
pkg_upstream_url="https://sourceforge.net/projects/sshpass/"
