pkg_name=sysstat
pkg_origin=core
pkg_version=11.7.4
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_description="Performance monitoring tools for Linux; provides: iostat, mpstat, pidstat, sar, sa1, sa2 and sadf"
pkg_upstream_url="https://github.com/sysstat/sysstat"
pkg_license=('GPL-2.0')
pkg_source="https://github.com/sysstat/sysstat/archive/refs/tags/v${pkg_version}.tar.gz"
pkg_shasum="3c7647c2f8cee0c586803614a875354921397b37abd298d55f416fb36016afbc"
pkg_deps=(core/glibc)
pkg_build_deps=(core/make core/gcc)
pkg_bin_dirs=(bin)
pkg_include_dirs=(include)
pkg_lib_dirs=(lib)
