[server]
host = "{{cfg.service.host}}"
port = "{{cfg.service.port}}"

[logger]
level = "{{cfg.log_level}}"

[admin]
username = "{{cfg.admin.username}}"
password = "{{cfg.admin.password}}"

[database]
type = "postgres"

[database.postgres]
{{#if bind.database}}
{{~#eachAlive bind.database.members as |member|}}
datasourcename = "postgres://{{cfg.storage.user}}:{{cfg.storage.password}}@{{member.sys.ip}}:{{member.cfg.port}}/{{cfg.storage.database}}?sslmode={{cfg.storage.ssl_mode}}"
{{~/eachAlive}}
{{else}}
{{#with cfg.storage}}
datasourcename = "postgres://{{user}}:{{password}}@{{host}}:{{port}}/{{database}}?sslmode={{ssl_mode}}"
{{/with}}
{{~/if}}

[authenticator]
type = "{{cfg.authenticator.type}}"
