#!/bin/sh

touch "{{pkg.svc_data_path}}/cursor-state"
touch "{{pkg.svc_data_path}}/pending-queue"

{{~#if cfg.logzio_codec}}
wget \
  --quiet \
  --output-document={{pkg.svc_config_path}}/certificate.crt \
  https://raw.githubusercontent.com/logzio/public-certificates/master/COMODORSADomainValidationSecureServerCA.crt
{{~/if}}
