#!/bin/bash

touch "{{pkg.svc_data_path}}/cursor-state"
touch "{{pkg.svc_data_path}}/pending-queue"

wget \
  --quiet \
  https://raw.githubusercontent.com/logzio/public-certificates/master/COMODORSADomainValidationSecureServerCA.crt \
  --output-document={{pkg.svc_config_path}}/certificate.crt
