#!/bin/bash -xe

exec 2>&1

SERVERMODE={{cfg.server.mode}}
export CONSUL_UI_BETA={{cfg.server.beta_ui}}

if [ "$SERVERMODE" = true ] ; then
  exec consul agent {{~#if cfg.website}} -ui {{~/if}} -server -bootstrap-expect {{cfg.bootstrap.expect}} -config-file={{pkg.svc_config_path}}/basic_config.json
else
  exec consul agent -dev
fi
