#!/bin/sh

debug() { if [ ! -z "$DEBUG" ]; then echo "$*"; fi }

echo "Preparing TOMCAT_HOME..."

debug "sys.ip        = {{sys.ip}}"
debug "sys.hostname  = {{sys.hostname}}"
debug "pkg.origin    = {{pkg.origin}}"
debug "pkg.name      = {{pkg.name}}"
debug "pkg.version   = {{pkg.version}}"
debug "pkg.release   = {{pkg.release}}"
debug "pkg.ident     = {{pkg.ident}}"
debug "pkg.deps      = {{pkg.deps}}"
debug "pkg.exposes   = {{pkg.exposes}}"
debug "pkg.svc_path          = {{pkg.svc_path}}"
debug "pkg.svc_config_path   = {{pkg.svc_config_path}}"
debug "pkg.svc_data_path     = {{pkg.svc_data_path}}"
debug "pkg.svc_files_path    = {{pkg.svc_files_path}}"
debug "pkg.svc_static_path   = {{pkg.svc_static_path}}"
debug "pkg.svc_var_path      = {{pkg.svc_var_path}}"

# Move directories that ship in the package into place

cp -R {{pkg.path}}/tc {{pkg.svc_var_path}}/

# Symlink config files into $TOMCAT_HOME/conf
for file in $(cd {{pkg.svc_config_path}}; ls -1)
do
  echo "Linking $file"
  target="${file//_//}"
  ln -vsf {{pkg.svc_config_path}}/$file {{pkg.svc_var_path}}/tc/$target
done

chown -R hab:hab {{pkg.svc_path}}/*

echo "Done preparing TOMCAT_HOME"
