#!/bin/bash

exec 2>&1

echo "Starting Apache Tomcat"

if path=$(hab pkg path core/jdk8); then
  export JAVA_HOME=$path
elif path=$(hab pkg path core/jdk7); then
  export JAVA_HOME=$path
fi
if path=$(hab pkg path core/jre8); then
  export JRE_HOME=$path
elif path=$(hab pkg path core/jre7); then
  export JRE_HOME=$path
fi
if [ -z ${JAVA_HOME+x} ] || [ -z ${JRE_HOME+x} ]; then
  echo "Cannot start Tomcat without core/jdk8, core/jdk7, core/jre8, or core/jre7"
  exit 1
fi

export TOMCAT_HOME="{{pkg.svc_var_path}}/tc"
export CATALINA_OPTS="{{cfg.server.catalina-opts}}"

echo "Executing Tomcat here: ${TOMCAT_HOME}/bin/catalina.sh"
exec ${TOMCAT_HOME}/bin/catalina.sh run
