#!/bin/bash

# Ensure privileged separation directory is present with
# correct permissions
mkdir -p {{pkg.path}}/var/empty
chmod 0700 {{pkg.path}}/var/empty

# Generate the keys if they do not exist - restarting sshd would cause
# this to fail, e.g., on package upgrade
if [ ! -f {{pkg.svc_config_path}}/ssh_host_dsa_key ]; then
  ssh-keygen -t dsa -f {{pkg.svc_config_path}}/ssh_host_dsa_key -N ""
fi

if [ ! -f {{pkg.svc_config_path}}/ssh_host_rsa_key ]; then
  ssh-keygen -t rsa -f {{pkg.svc_config_path}}/ssh_host_rsa_key -N ""
fi

if [ ! -f {{pkg.svc_config_path}}/ssh_host_ed25519_key ]; then
  ssh-keygen -t ed25519 -f {{pkg.svc_config_path}}/ssh_host_ed25519_key -N ""
fi

if [ ! -f {{pkg.svc_config_path}}/ssh_host_ecdsa_key ]; then
  ssh-keygen -t ecdsa -f {{pkg.svc_config_path}}/ssh_host_ecdsa_key -N ""
fi
