version: '2'
services:
  zookeeper:
    image: core/zookeeper
    ports:
      - "2181:2181"
    environment:
      - HAB_LICENSE=accept-no-persist
  kafka:
    image: core/kafka
    links:
      - zookeeper
    command: --peer zookeeper --bind zookeeper:zookeeper.default
    environment:
      - HAB_LICENSE=${HAB_LICENSE}
