#!/bin/bash

exec 2>&1

echo "Starting Apache Tomcat"

if path=$(hab pkg path core/jdk8); then
  export JAVA_HOME=$path
elif path=$(hab pkg path core/jdk7); then
  export JAVA_HOME=$path
fi
if [ -z ${JAVA_HOME+x} ]; then
  echo "Cannot start Tomcat without core/jdk8 or core/jdk7"
  exit 1
fi

export CATALINA_HOME="{{pkg.svc_var_path}}"
export CATALINA_OPTS="{{cfg.server.catalina-opts}}"

cd {{pkg.svc_var_path}}
echo "Executing Tomcat here: {{pkg.svc_var_path}}/bin/catalina.sh"
exec {{pkg.svc_var_path}}/bin/catalina.sh run
