#!/bin/bash

set -e

export SHIELD_API_TOKEN="${SHIELD_API_TOKEN:-autoprovision}"
export SHIELD_SKIP_SSL_VERIFY=TRUE

echo "CONFIGURING SHIELD AT ${SHIELD_ENDPOINT}"
echo "> Targeting backend at ${SHIELD_ENDPOINT}"
shield create-backend test-shield https://"${SHIELD_ENDPOINT}"
shield backend

shield "${1}" "${2}"
