#!/bin/sh

exec 2>&1

export USE_RUBY=1

# The `path.logs' config is no-op as we disable all file based logging
# via a custom `log4j2.properites' file. We only set it so a hard-coded
# and confusing `puts' message is not printed during startup. Habitat
# apps should just print log messages to the console!
exec {{pkg.path}}/bin/logstash \
  --path.config {{pkg.svc_config_path}} \
  --path.data {{pkg.svc_var_path}}/data \
  --path.logs {{pkg.svc_var_path}}/log \
  --path.settings {{pkg.path}}/settings
