pkg_name=libxslt
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_description="Libxslt is the XSLT C library developed for the GNOME project"
pkg_upstream_url=http://xmlsoft.org/XSLT/
pkg_version=1.1.34
pkg_origin=core
pkg_license=('libxslt')
pkg_source=http://xmlsoft.org/sources/libxslt-${pkg_version}.tar.gz
pkg_filename=libxslt-${pkg_version}.tar.gz
pkg_shasum=98b1bd46d6792925ad2dfe9a87452ea2adebf69dcb9919ffd55bf926a7f93f7f
pkg_deps=(core/glibc core/libxml2 core/zlib)
pkg_build_deps=(core/coreutils core/patch core/make core/gcc)
pkg_bin_dirs=(bin)
pkg_lib_dirs=(lib)
pkg_include_dirs=(include)
