#!/bin/bash

hab svc unload starkandwayne/shield-agent

{{ #unless svc.me.follower }}
mkdir -p /hab/svc/shield-agent
cp {{pkg.svc_config_path}}/shield-agent.toml /hab/svc/shield-agent/user.toml
hab svc load starkandwayne/shield-agent --group {{svc.group}}
{{~/unless}}
