pkg_name=protobuf2.5
pkg_distname=protobuf
pkg_origin=core
pkg_version=2.5.0
pkg_license=('BSD-3-Clause')
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_source=https://github.com/google/${pkg_distname}/releases/download/v${pkg_version}/${pkg_distname}-${pkg_version}.tar.bz2
pkg_dirname="$pkg_distname-$pkg_version"
pkg_shasum=13bfc5ae543cf3aa180ac2485c0bc89495e3ae711fc6fab4f8ffe90dfb4bb677
pkg_deps=(core/gcc core/zlib)
pkg_build_deps=(core/make)
pkg_bin_dirs=(bin)
pkg_lib_dirs=(lib)
pkg_include_dirs=(include)
pkg_upstream_url=https://github.com/google/protobuf
pkg_description="Protocol Buffers - Google's data interchange format https://developers.google.com/protocol-buffers/"
